### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by zgaop** [maruohon/malilib#110]
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-01-21 15:30:21
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 257
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327.method_27516(class_327.java:57)
	at net.minecraft.class_5225.method_27496(class_5225.java:41)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5223.method_27472(class_5223.java:84)
	at net.minecraft.class_5223.method_27479(class_5223.java:80)
	at net.minecraft.class_5225.method_27482(class_5225.java:40)
	at net.minecraft.class_327.method_1727(class_327.java:364)
	at fi.dy.masa.malilib.render.RenderUtils.renderText(RenderUtils.java:408)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:147)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$eom000$onGameOverlayPost(class_329.java:11484)
	at net.minecraft.class_329.method_1753(class_329.java:394)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327.method_27516(class_327.java:57)
	at net.minecraft.class_5225.method_27496(class_5225.java:41)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5223.method_27472(class_5223.java:84)
	at net.minecraft.class_5223.method_27479(class_5223.java:80)
	at net.minecraft.class_5225.method_27482(class_5225.java:40)
	at net.minecraft.class_327.method_1727(class_327.java:364)
	at fi.dy.masa.malilib.render.RenderUtils.renderText(RenderUtils.java:408)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:147)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$eom000$onGameOverlayPost(class_329.java:11484)
	at net.minecraft.class_329.method_1753(class_329.java:394)

-- Affected level --
Details:
	All players: 1 total; [class_746['zgaop'/6897, l='ClientLevel', x=1.16, y=68.00, z=-294.16]]
	Chunk stats: 16384, 464
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,67,-271), Section: (at 0,3,1 in -1,4,-17; chunk contains blocks -16,-64,-272 to -1,319,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 970529 game time, 967146 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-1o2-Fabric.zip, 思源黑体.zip, XPlus 配套基础材质[masa汉化][反南瓜头GUI]v0.0.3.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2869148440 bytes (2736 MiB) / 4160749568 bytes (3968 MiB) up to 7348420608 bytes (7008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce 940MX
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x134d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2802
	Graphics card #1 name: Intel(R) HD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x5916
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 11679.83
	Virtual memory used (MB): 10360.19
	Swap memory total (MB): 3589.55
	Swap memory used (MB): 142.62
	JVM Flags: 11 total; -Xmx7000m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		advancementplaques: Advancement Plaques 1.4.6
		ae2: Applied Energistics 2 12.9.2
			noindium: No Indium? 1.1.0+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.56
		armorchroma: Armor Chroma 1.2.2
		autofish: Autofish 0.9.5-SNAPSHOT
		badpackets: Bad Packets 0.2.1
		bgmselector: Background Music Selector 1.0-SNAPSHOT
		bookshelf: Bookshelf 16.1.11
		botania: Botania 1.19.2-436-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.84
		carpet-extra: Carpet Extra 1.4.84
		chat_heads: Chat Heads 0.7.1
		clear-skies: Clear Skies 2.0.95
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		colormatic: Colormatic 3.1.2+mc.1.19
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.4
		cullparticles: Cull Particles 2.0
		customskinloader: CustomSkinLoader 14.15-SNAPSHOT-348
		customwindowtitle: Custom Window Title 1.1.1
		debugify: Debugify 2.8.0
		draggable-resource-packs: Draggable Resource Packs 3.0.1+build.9
		durabilityviewer: Giselbaers Durability Viewer 1.19.1-fabric0.58.5-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easiervillagertrading: EasierVillagerTrading 1.19.1-fabric0.58.5-1.5.4
		enchdesc: EnchantmentDescriptions 13.0.10
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		essential-client: Essential Client 1.2.4
			com_github_senseiwells_arucas: Arucas ad5c8f55fcb5efb33e9f281dbe2d3d752627adc3
			com_github_senseiwells_arucasdiscordapi: ArucasDiscordAPI v1.0.0
			multiconnect-api: MultiConnect API 1.5.10
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farsight: Farsight Mod 1.19-2.1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.10
		gammautils: Gamma Utils 1.6.10
		held-item-info: Held Item Info 1.3.0
		i18nupdatemod: I18nUpdateMod 3.2.0
		ias: In-Game Account Switcher 8.0.1
		ic2: Industrial Craft 2 2.9.21+ex119
		ic2fix: IC2Fix 1.0.0
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		ingameime: IngameIME 1.6.6
		inventoryprofilesnext: Inventory Profiles Next 1.8.5
		iris: Iris 1.4.2
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		ironchests: Iron Chests 1.7.7
			libgui: LibGui 6.2.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		itemscroller: Item Scroller 0.17.1
		java: Java HotSpot(TM) 64-Bit Server VM 19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 1.0.6
		litematica: Litematica 0.12.5
		lithium: Lithium 0.10.2
		magiclib: MagicLib 0.5.37
			magiclib-1_19_2: MagicLib for 1.19.2 0.5.37
		malilib: MaLiLib 0.13.0
		masa_gadget_mod-1_19_2: Masa Gadget for 1.19.2 3.0.0-beta+bc54082
		megane: megane 8.3.0
			megane-api: megane-api 8.3.0
			megane-applied-energistics-2: megane-applied-energistics-2 8.3.0
			megane-fabric-transfer: megane-fabric-transfer 8.3.0
			megane-reborn-energy: megane-reborn-energy 8.3.0
			megane-runtime: megane-runtime 8.3.0
			megane-vanilla: megane-vanilla 8.3.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modern_industrialization: Modern Industrialization 1.4.1
			magna: Magna 1.8.0-1.19
			playerabilitylib: Pal 1.6.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 4.1.2
		moreculling: More Culling 1.19.1-0.14.0
			conditional-mixin: conditional mixin 0.3.0
		notenoughanimations: NotEnoughAnimations 1.6.2
		ommc-1_19_2: Oh My Minecraft Client for 1.19.2 0.5-beta+657858c
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		orderly: Orderly 2.0.1-alpha.2+custom-1.19
		patchouli: Patchouli 1.19.2-77-FABRIC
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		roughlyenoughitems: Roughly Enough Items 9.1.572
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		satin: Satin 1.9.0
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		slight-gui-modifications: 'Slight' GUI Modifications 2.3.0
			org_codehaus_groovy_groovy: groovy 3.0.11
			org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.11
		smoothswapping: Smooth Swapping 0.4.4
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.13+mc1.19.2-build.76
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		terrablender: TerraBlender 2.0.1.130
		torcherino: Torcherino 17.0.1
		trinkets: Trinkets 3.4.2
		tweakeroo: Tweakeroo 0.14.2
		tweakmyclient: Tweak My Client 3.4.292+e714e26-beta
			tweakmyclient-1_19_2: Tweak My Client for 1.19.2 3.4.292+e714e26-beta
		twilightforest: The Twilight Forest 4.2.333
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.642+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.642+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.642+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.642+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.642+1.19.2
				porting_lib_models: Porting Lib Models 2.1.642+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.642+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.642+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.642+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.642+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.642+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.642+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.642+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.642+1.19.2
						porting_lib_common: Porting Lib Common 2.1.642+1.19.2
		viafabric: ViaFabric 0.4.9+21-main
			org_yaml_snakeyaml: snakeyaml 1.33
			viafabric-mc119: ViaFabric for 1.19 0.4.9+21-main
			viaversion: ViaVersion 4.4.3-SNAPSHOT
		visualworkbench: Visual Workbench 4.2.1
		wi_zoom: WI Zoom 1.4-MC1.19.2
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
		wthit: wthit 5.13.4
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: XPlus 2.0 based on Minecraft 1.19.2 (Fabric)
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce 940MX/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-1o2-Fabric.zip, file/思源黑体.zip, file/XPlus 配套基础材质[masa汉化][反南瓜头GUI]v0.0.3.zip
	Current Language: 简体中文 (中国大陆)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by maruohon** [comment]
Using Yarn names, `method_2011()` is `FontStorage#getGlyph()`, which then calls some FastUtils map stuff. This is in the vanilla code and then in FastUtils library code. So either it's related to your resource pack/font being broken somehow, or it's a vanilla bug, or some mod is changing something about the vanilla class or the FastUtils class that breaks it.

I guess try without any active resource packs first, and if it still crashes, then try without any other mods than malilib and MiniHUD.
