### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by CharisSophia** [maruohon/malilib#29]
I am attempting to create a MultiMC instance for Litematica. I install Fabric and the game runs. Add Fabric API and the game runs. Add malilib and it crashes on launch.

_________________
MultiMC version: 0.6.11-1370

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/.minecraft

Java path is:
/usr/bin/java

Java is version 10, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-remapper/0.2.2.64/tiny-remapper-0.2.2.64.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm/8.0/asm-8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-analysis/8.0/asm-analysis-8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-commons/8.0/asm-commons-8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-tree/8.0/asm-tree-8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-util/8.0/asm-util-8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader/0.9.0+build.204/fabric-loader-0.9.0+build.204.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.16.1/minecraft-1.16.1-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] fabric-api-0.15.1+build.380-1.16.1

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 1366 x 768

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.16.1 Voxelmap", -XstartOnFirstThread, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 12876

Using onesix launcher.

[14:29:52] [main/INFO]: Loading for game Minecraft 1.16.1
[14:29:53] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:600) ~[fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202) ~[fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to open mod JAR at /Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/.minecraft/mods/malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar!
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:933) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:583) ~[fabric-loader-0.9.0+build.204.jar:?]
	... 12 more
Caused by: java.lang.RuntimeException: Failed to open mod JAR at /Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/.minecraft/mods/malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar!
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:456) ~[fabric-loader-0.9.0+build.204.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Process exited with code 1.
Clipboard copy at: 20 Jul 2020 14:34:10 -0700

**Comment by CharisSophia** [comment]
I'm running on Mac OSX.

**Comment by maruohon** [comment]
```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to open mod JAR at /Applications/MultiMC.app/Contents/MacOS/instances/1.16.1 Voxelmap/.minecraft/mods/malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar
```
Is the mod file corrupted during download maybe? Or a permission issue of some kind?

**Comment by CharisSophia** [comment]
Ah! Permissions! When I went looking for that, I discovered I didn't copy the file in right. It's an alias.

Thank you! That's exactly what I needed. :)
