### ISSUE TITLE
minihud-fabric-1.19.2-0.23.3.jar crash

### ISSUE THREAD

**Issue by Vid0Vid0** [maruohon/malilib#92]
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index -6 out of bounds for length 100
	at fi.dy.masa.minihud.util.DataStorage.onClientTickPre(DataStorage.java:339)
	at net.minecraft.class_310.handler$zke000$onClientTickPre(class_310.java:6447)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Thread: Render thread
Stacktrace:
	at fi.dy.masa.minihud.util.DataStorage.onClientTickPre(DataStorage.java:339)
	at net.minecraft.class_310.handler$zke000$onClientTickPre(class_310.java:6447)

fabricloader: Fabric Loader 0.14.9
java: OpenJDK 64-Bit Server VM 17
malilib: MaLiLib 0.13.0
minecraft: Minecraft 1.19.2
minihud: MiniHUD 0.23.3
Launched Version: fabric-loader-0.14.9-1.19.2

**Comment by maruohon** [comment]
If this is in single player, can you send me the `level.dat`  file of that world? Or you could also just do `/time query gametime` and post the result.

**Comment by Vid0Vid0** [comment]
MiniHud crashes when opening old worlds with an invalid value (e.g. -2^63+1) in the Time field of the level.dat file.
